sudo: false

# Use the original Go 1.11 instead of the Go 1.11 installed by gimme.
# It looks like gimme Go causes some errors on go-test for Wasm.

install:
  - unset GOROOT
  - wget -O go.tar.gz https://dl.google.com/go/go1.11.4.linux-amd64.tar.gz
  - mkdir ~/gocode
  - tar -C ~/gocode -xzf go.tar.gz
  - rm go.tar.gz
  - export PATH=~/gocode/go/bin:$PATH
  - go get golang.org/dl/go1.12beta1
  - go1.12beta1 download
  - nvm install node
  - nvm use node
  - mkdir /tmp/work
  - cd /tmp/work
  - go mod init example.com/m
  - go get github.com/gopherjs/gopherwasm@$TRAVIS_BRANCH
  - GO111MODULE=off go get github.com/gopherjs/gopherjs/...
  - GO111MODULE=off go get github.com/gopherjs/gopherwasm/...

script:
  - cd /tmp/work
  - PATH=$(go env GOROOT)/misc/wasm:$PATH GOOS=js GOARCH=wasm go test github.com/gopherjs/gopherwasm/js/...
  - PATH=$(go1.12beta1 env GOROOT)/misc/wasm:$PATH GOOS=js GOARCH=wasm go1.12beta1 test github.com/gopherjs/gopherwasm/js/...
  - gopherjs test github.com/gopherjs/gopherwasm/js/...
